const express = require('express');
const crypto = require('crypto');
const prisma = require('../config/prisma');
const adminAuth = require('../middleware/adminAuth');

const router = express.Router();
router.use(adminAuth);

function generateKeyPair() {
  const apiKey = 'hub_pk_' + crypto.randomBytes(16).toString('hex');
  const apiSecret = 'hub_sk_' + crypto.randomBytes(32).toString('hex');
  return { apiKey, apiSecret };
}

// Register one of your 10 websites. Call this once per site, save the returned
// apiKey + apiSecret into that site's environment variables (never commit them).
router.post('/merchants', async (req, res, next) => {
  try {
    const { name, webhookUrl } = req.body;
    if (!name || !webhookUrl) {
      return res.status(400).json({ status: false, message: 'name and webhookUrl are required' });
    }

    const { apiKey, apiSecret } = generateKeyPair();

    const merchant = await prisma.merchant.create({
      data: { name, webhookUrl, apiKey, apiSecret },
    });

    // apiSecret is only ever shown once, right here — store it safely on the merchant site now.
    res.status(201).json({
      status: true,
      message: 'Merchant registered. Store apiSecret now — it will not be shown again.',
      data: {
        id: merchant.id,
        name: merchant.name,
        apiKey: merchant.apiKey,
        apiSecret: merchant.apiSecret,
        webhookUrl: merchant.webhookUrl,
      },
    });
  } catch (err) {
    next(err);
  }
});

router.get('/merchants', async (req, res, next) => {
  try {
    const merchants = await prisma.merchant.findMany({
      select: { id: true, name: true, apiKey: true, webhookUrl: true, isActive: true, createdAt: true },
    });
    res.json({ status: true, data: merchants });
  } catch (err) {
    next(err);
  }
});

// Review a single already-registered site, including its apiSecret. The list view
// (GET /merchants) deliberately omits apiSecret so it's never sat in a bulk response;
// this endpoint is the explicit, one-at-a-time "reveal" for when you've lost track of
// a secret you already generated. Still gated by the same admin key as everything else.
router.get('/merchants/:id', async (req, res, next) => {
  try {
    const merchant = await prisma.merchant.findUnique({ where: { id: req.params.id } });
    if (!merchant) return res.status(404).json({ status: false, message: 'Not found' });

    res.json({
      status: true,
      data: {
        id: merchant.id,
        name: merchant.name,
        apiKey: merchant.apiKey,
        apiSecret: merchant.apiSecret,
        webhookUrl: merchant.webhookUrl,
        isActive: merchant.isActive,
        createdAt: merchant.createdAt,
      },
    });
  } catch (err) {
    next(err);
  }
});

router.patch('/merchants/:id/toggle', async (req, res, next) => {
  try {
    const merchant = await prisma.merchant.findUnique({ where: { id: req.params.id } });
    if (!merchant) return res.status(404).json({ status: false, message: 'Not found' });

    const updated = await prisma.merchant.update({
      where: { id: req.params.id },
      data: { isActive: !merchant.isActive },
    });
    res.json({ status: true, data: { id: updated.id, isActive: updated.isActive } });
  } catch (err) {
    next(err);
  }
});

// Permanently delete a site's API key/secret. Blocked if the merchant has any
// transaction history — deleting the merchant row would either orphan or (via FK
// constraint) simply fail against those transaction records, and silently losing
// payment history is worse than a clear error. Deactivate (above) is the right move
// for a site you want to cut off but still keep records for; this is for a key that
// was generated by mistake, for a test, or never actually put into use.
router.delete('/merchants/:id', async (req, res, next) => {
  try {
    const merchant = await prisma.merchant.findUnique({ where: { id: req.params.id } });
    if (!merchant) return res.status(404).json({ status: false, message: 'Not found' });

    const transactionCount = await prisma.transaction.count({ where: { merchantId: merchant.id } });
    if (transactionCount > 0) {
      return res.status(409).json({
        status: false,
        message: `Cannot delete "${merchant.name}" — it has ${transactionCount} transaction(s) on record. Deactivate it instead to preserve payment history.`,
      });
    }

    await prisma.merchant.delete({ where: { id: merchant.id } });
    res.json({ status: true, message: `"${merchant.name}" deleted.` });
  } catch (err) {
    next(err);
  }
});

// Serializes a transaction row for the successful-transactions admin view, including
// the customer-facing "user detail" fields (email, amount, which merchant site, etc.)
// but never any merchant apiKey/apiSecret.
function serializeTransaction(tx) {
  return {
    id: tx.id,
    reference: tx.reference,
    status: tx.status,
    email: tx.email,
    amountKobo: tx.amountKobo.toString(),
    amount: Number(tx.amountKobo) / 100,
    currency: tx.currency,
    merchant: tx.merchant ? { id: tx.merchant.id, name: tx.merchant.name } : null,
    metadata: tx.metadata ? JSON.parse(tx.metadata) : null,
    createdAt: tx.createdAt,
    updatedAt: tx.updatedAt,
  };
}

// Lists only SUCCESS transactions, newest first, with the paying customer's email
// and which merchant site the payment belongs to. This is deliberately a separate
// endpoint from a general transaction list — the admin portal that calls this only
// ever needs to see completed payments, not every pending/failed attempt.
router.get('/transactions/successful', async (req, res, next) => {
  try {
    const transactions = await prisma.transaction.findMany({
      where: { status: 'SUCCESS' },
      include: { merchant: { select: { id: true, name: true } } },
      orderBy: { createdAt: 'desc' },
    });
    res.json({ status: true, data: transactions.map(serializeTransaction) });
  } catch (err) {
    next(err);
  }
});

// Deletes a transaction, but ONLY if it's a SUCCESS record — this endpoint backs the
// "delete a successful one" action in the admin portal and intentionally refuses to
// touch PENDING/FAILED/ABANDONED rows (there's no product reason to delete those from
// here, and scoping the check server-side means a compromised/buggy admin UI can't be
// used to quietly wipe other transaction history).
router.delete('/transactions/:id', async (req, res, next) => {
  try {
    const transaction = await prisma.transaction.findUnique({ where: { id: req.params.id } });
    if (!transaction) return res.status(404).json({ status: false, message: 'Not found' });

    if (transaction.status !== 'SUCCESS') {
      return res.status(409).json({
        status: false,
        message: `Only SUCCESS transactions can be deleted from this endpoint (this one is ${transaction.status}).`,
      });
    }

    await prisma.transaction.delete({ where: { id: transaction.id } });
    res.json({ status: true, message: `Transaction ${transaction.reference} deleted.` });
  } catch (err) {
    next(err);
  }
});

module.exports = router;
