const express = require('express');
const crypto = require('crypto');
const prisma = require('../config/prisma');
const adminAuth = require('../middleware/adminAuth');

const router = express.Router();
router.use(adminAuth);

function generateKeyPair() {
  const apiKey = 'hub_pk_' + crypto.randomBytes(16).toString('hex');
  const apiSecret = 'hub_sk_' + crypto.randomBytes(32).toString('hex');
  return { apiKey, apiSecret };
}

// Register one of your 10 websites. Call this once per site, save the returned
// apiKey + apiSecret into that site's environment variables (never commit them).
router.post('/merchants', async (req, res, next) => {
  try {
    const { name, webhookUrl } = req.body;
    if (!name || !webhookUrl) {
      return res.status(400).json({ status: false, message: 'name and webhookUrl are required' });
    }

    const { apiKey, apiSecret } = generateKeyPair();

    const merchant = await prisma.merchant.create({
      data: { name, webhookUrl, apiKey, apiSecret },
    });

    // apiSecret is only ever shown once, right here — store it safely on the merchant site now.
    res.status(201).json({
      status: true,
      message: 'Merchant registered. Store apiSecret now — it will not be shown again.',
      data: {
        id: merchant.id,
        name: merchant.name,
        apiKey: merchant.apiKey,
        apiSecret: merchant.apiSecret,
        webhookUrl: merchant.webhookUrl,
      },
    });
  } catch (err) {
    next(err);
  }
});

router.get('/merchants', async (req, res, next) => {
  try {
    const merchants = await prisma.merchant.findMany({
      select: { id: true, name: true, apiKey: true, webhookUrl: true, isActive: true, createdAt: true },
    });
    res.json({ status: true, data: merchants });
  } catch (err) {
    next(err);
  }
});

// Review a single already-registered site, including its apiSecret. The list view
// (GET /merchants) deliberately omits apiSecret so it's never sat in a bulk response;
// this endpoint is the explicit, one-at-a-time "reveal" for when you've lost track of
// a secret you already generated. Still gated by the same admin key as everything else.
router.get('/merchants/:id', async (req, res, next) => {
  try {
    const merchant = await prisma.merchant.findUnique({ where: { id: req.params.id } });
    if (!merchant) return res.status(404).json({ status: false, message: 'Not found' });

    res.json({
      status: true,
      data: {
        id: merchant.id,
        name: merchant.name,
        apiKey: merchant.apiKey,
        apiSecret: merchant.apiSecret,
        webhookUrl: merchant.webhookUrl,
        isActive: merchant.isActive,
        createdAt: merchant.createdAt,
      },
    });
  } catch (err) {
    next(err);
  }
});

router.patch('/merchants/:id/toggle', async (req, res, next) => {
  try {
    const merchant = await prisma.merchant.findUnique({ where: { id: req.params.id } });
    if (!merchant) return res.status(404).json({ status: false, message: 'Not found' });

    const updated = await prisma.merchant.update({
      where: { id: req.params.id },
      data: { isActive: !merchant.isActive },
    });
    res.json({ status: true, data: { id: updated.id, isActive: updated.isActive } });
  } catch (err) {
    next(err);
  }
});

// Permanently delete a site's API key/secret. Blocked if the merchant has any
// transaction history — deleting the merchant row would either orphan or (via FK
// constraint) simply fail against those transaction records, and silently losing
// payment history is worse than a clear error. Deactivate (above) is the right move
// for a site you want to cut off but still keep records for; this is for a key that
// was generated by mistake, for a test, or never actually put into use.
router.delete('/merchants/:id', async (req, res, next) => {
  try {
    const merchant = await prisma.merchant.findUnique({ where: { id: req.params.id } });
    if (!merchant) return res.status(404).json({ status: false, message: 'Not found' });

    const transactionCount = await prisma.transaction.count({ where: { merchantId: merchant.id } });
    if (transactionCount > 0) {
      return res.status(409).json({
        status: false,
        message: `Cannot delete "${merchant.name}" — it has ${transactionCount} transaction(s) on record. Deactivate it instead to preserve payment history.`,
      });
    }

    await prisma.merchant.delete({ where: { id: merchant.id } });
    res.json({ status: true, message: `"${merchant.name}" deleted.` });
  } catch (err) {
    next(err);
  }
});

// GET /admin/transactions — successful payments only, across all registered sites,
// newest first. Cursor-paginated (not offset) so it stays fast as the table grows.
// Optional ?merchantId=... to filter to one site, ?q=... to search email/reference.
router.get('/transactions', async (req, res, next) => {
  try {
    const take = Math.min(Number(req.query.limit) || 30, 100);
    const { merchantId, cursor, q } = req.query;

    const where = { status: 'SUCCESS' };
    if (merchantId) where.merchantId = merchantId;
    if (q) {
      where.OR = [
        { email: { contains: q } },
        { reference: { contains: q } },
      ];
    }

    const rows = await prisma.transaction.findMany({
      where,
      include: { merchant: { select: { id: true, name: true } } },
      orderBy: { createdAt: 'desc' },
      take: take + 1,
      ...(cursor ? { cursor: { id: cursor }, skip: 1 } : {}),
    });

    let nextCursor = null;
    if (rows.length > take) nextCursor = rows.pop().id;

    const data = rows.map((t) => ({
      id: t.id,
      reference: t.reference,
      amount: Number(t.amountKobo) / 100,
      currency: t.currency,
      email: t.email,
      metadata: t.metadata ? JSON.parse(t.metadata) : null,
      createdAt: t.createdAt,
      site: { id: t.merchant.id, name: t.merchant.name },
    }));

    res.json({ status: true, data, nextCursor });
  } catch (err) {
    next(err);
  }
});

// GET /admin/transactions/summary — totals for the dashboard header: overall
// successful count + revenue per currency, and a per-site breakdown so you can
// see at a glance which of the 10 sites is driving volume.
router.get('/transactions/summary', async (req, res, next) => {
  try {
    const successWhere = { status: 'SUCCESS' };

    const [totalCount, byCurrency, merchants, perMerchant] = await Promise.all([
      prisma.transaction.count({ where: successWhere }),
      prisma.transaction.groupBy({ by: ['currency'], where: successWhere, _sum: { amountKobo: true } }),
      prisma.merchant.findMany({ select: { id: true, name: true, isActive: true } }),
      prisma.transaction.groupBy({ by: ['merchantId', 'currency'], where: successWhere, _sum: { amountKobo: true }, _count: true }),
    ]);

    const merchantMap = Object.fromEntries(merchants.map((m) => [m.id, m]));
    const siteBreakdown = perMerchant.map((row) => ({
      site: merchantMap[row.merchantId]?.name || 'Unknown',
      siteId: row.merchantId,
      currency: row.currency,
      count: row._count,
      total: Number(row._sum.amountKobo || 0n) / 100,
    }));

    res.json({
      status: true,
      data: {
        totalSuccessful: totalCount,
        totals: byCurrency.map((c) => ({ currency: c.currency, total: Number(c._sum.amountKobo || 0n) / 100 })),
        sites: siteBreakdown,
        siteCount: merchants.length,
      },
    });
  } catch (err) {
    next(err);
  }
});

module.exports = router;
